version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=max
    # MONGO_INITDB_ROOT_USERNAME: john
    # MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DEFAULT_PORT: 5000
    ports:
      - "80:5000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./

  # frontend:
volumes:
  mongo-data:
  logs:
