version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=max
    # MONGO_INITDB_ROOT_USERNAME: john
    # MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env

  # backend:
  # frontend:
volumes:
  mongo-data:
